name: Terrform Integrated GitHub Actions Workflow

on:
	workflow_dispatch: 
    
jobs:
	terraform:
    	name: Terraform
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        steps:
        	- name: Terraform Init
              id: init
              run: terraform init
              
            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color
              
            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color -input=false
              
            - name: Terraform Apply
              id: apply
              run: terraform apply -auto-approve -input=false
              
